[package]
name = "revvy02/jam"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
jabby = "alicesaidhi/jabby@0.1.0"
jecs = "ukendio/jecs@0.2.10"