[package]
name = "ashleyflow/jam"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Jabby = "alicesaidhi/jabby@0.1.0"
Jecs = "ukendio/jecs@0.3.2"
