[package]
name = "revvy02/jam"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Jabby = "alicesaidhi/jabby@0.1.0"
Jecs = "ukendio/jecs@0.3.2"
